inherits = "catppuccin_mocha"

"ui.background" = { bg = "default" }
"ui.gutter" = { bg = "default" }
"ui.statusline" = { bg = "default" }
"ui.popup" = { bg = "default" }
"ui.menu" = { bg = "default" }
"ui.help" = { bg = "default" }
